version: '3'

services:
  api_cqrs:
    container_name: api_cqrs
    env_file: .env.example
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - write_db
      - read_db

  write_db:
    container_name: write_db
    env_file: .env.example
    environment:
      - POSTGRES_USER=${WRITE_DB_USERNAME}
      - POSTGRES_PASSWORD=${WRITE_DB_PASSWORD}
      - POSTGRES_DB=${WRITE_DB_DATABASE}
      - POSTGRES_USER_HOSTNAME=${WRITE_DB_HOSTNAME}
    build:
      context: ./database
      dockerfile: Dockerfile
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5420:5432'

  read_db:
    container_name: read_db
    image: mongo:latest
    ports:
      - '27020:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  pg_data:
  mongo_data:
