version: '3'

services:
  api:
    env_file: .env.example
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - write_bd
      - read_db

  write_bd:
    container_name: write_bd
    env_file: .env.example
    build:
      context: ./database
      dockerfile: Dockerfile
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  read_db:
    container_name: read_db
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  pg_data:
  mongo_data:
